apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kastro-ingress
  namespace: default
  annotations:
   
    alb.ingress.kubernetes.io/scheme: internet-facing
    
    # Directs traffic to Pod IPs (best for EKS)
    alb.ingress.kubernetes.io/target-type: ip
    
    # Optional: Groups multiple ingresses under one ALB to save costs
    alb.ingress.kubernetes.io/group.name: kastro-group
spec:
  # This matches the AWS Load Balancer Controller you just installed
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /about
        pathType: Prefix
        backend:
          service:
            name: about-service
            port:
              number: 80
      - path: /contact
        pathType: Prefix
        backend:
          service:
            name: contact-service
            port:
              number: 80
      - path: /services
        pathType: Prefix
        backend:
          service:
            name: services-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: techsolutions-service # Your main default service
            port:
              number: 80
