apiVersion: v1
kind: Service
metadata:
  name: about-service
  namespace: default
spec:
  selector:
    app: techsolutions # Change this to match the label in your about-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: contact-service
spec:
  selector:
    app: techsolutions
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: services-service
spec:
  selector:
    app: techsolutions
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
