apiVersion: v1
kind: Service
metadata:
  name: about-service
spec:
  selector:
    app: about # Change this to match the label in your about-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: contact-service
spec:
  selector:
    app: contact
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: services-service
spec:
  selector:
    app: services
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
